#!/usr/bin/env python3
"""
Push a snapshot of E:\\MyFantasyFootball\\sim_lab to the orphan `simlab-backup`
branch of the site repo (sibling of extensions-backup / functions-backup).

Steps: temp detached worktree on origin/simlab-backup -> wipe its sim_lab/ ->
copy the current folder in (same exclusions as the branch .gitignore) ->
`git add -f sim_lab .gitignore README.md` (sim_lab is whitelisted OUT by the
repo's .git/info/exclude, so -f on these explicit paths is required; never
`git add -A`) -> commit -> push -> remove the worktree.

Usage: python backup_to_branch.py ["commit message"]
"""
import fnmatch, os, shutil, subprocess, sys, tempfile, time

SRC = os.path.dirname(os.path.abspath(__file__))
REPO = r"E:\MyFantasyFootball\MyFantasyFootball Files"
BRANCH = "simlab-backup"
EXCL_DIRS = {"__pycache__", "field_cache", "field_out", "salary_cache"}
EXCL_GLOBS = ("*.pkl", "*.parquet", "*.bak*", "*.pyc")

def keep(rel, name):
    if any(fnmatch.fnmatch(name, g) for g in EXCL_GLOBS):
        return False
    if rel.replace("\\", "/") == "data" and name.endswith(".js") and name != "sim_tuning.js":
        return False  # data mirrors are regenerated by refresh_data.py
    return True

def git(*args, cwd=REPO, check=True):
    r = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, encoding="utf-8")
    if check and r.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed:\n{r.stderr}")
    return r.stdout.strip()

def main():
    msg = sys.argv[1] if len(sys.argv) > 1 else f"simlab-backup: sync {time.strftime('%Y-%m-%d %H:%M')}"
    git("fetch", "-q", "origin", BRANCH)
    wt = os.path.join(tempfile.gettempdir(), f"simlab_wt_{int(time.time())}")
    git("worktree", "add", "--detach", wt, f"origin/{BRANCH}")
    try:
        dst = os.path.join(wt, "sim_lab")
        if os.path.isdir(dst):
            shutil.rmtree(dst)
        n = 0
        for root, dirs, files in os.walk(SRC):
            dirs[:] = [d for d in dirs if d not in EXCL_DIRS]
            rel = os.path.relpath(root, SRC)
            for f in files:
                if not keep(rel, f):
                    continue
                d = os.path.join(dst, rel, f)
                os.makedirs(os.path.dirname(d), exist_ok=True)
                shutil.copy2(os.path.join(root, f), d)
                n += 1
        git("add", "-f", "sim_lab", ".gitignore", "README.md", cwd=wt)
        changed = git("diff", "--cached", "--stat", cwd=wt)
        if not changed:
            print(f"copied {n} files - nothing changed vs origin/{BRANCH}")
            return 0
        print(changed.splitlines()[-1])
        git("-c", "core.safecrlf=false", "commit", "-q", "-m", msg + "\n\nCo-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>", cwd=wt)
        git("push", "-q", "origin", f"HEAD:{BRANCH}", cwd=wt)
        print("pushed", git("log", "--oneline", "-1", cwd=wt))
        return 0
    finally:
        git("worktree", "remove", "--force", wt, check=False)
        git("worktree", "prune", check=False)

if __name__ == "__main__":
    sys.exit(main())
