#!/usr/bin/env python3
"""
ACTUAL RESULTS for the season sim (Jack 2026-10-02: "season sim shouldn't resimulate any games already played").

Writes data/sim_actuals_2026.js -> window.SIM_ACTUALS_2026 = {
  updated, season,
  done:  {wk: [team, ...]}        teams whose game that week is FINAL (kickoff + 5 hours, the rule the league sim uses)
  weeks: {wk: {sid: [pts_std, rec, pass_td, pass_yd, rush_yd, rush_td, rec_yd, rec_td]}}   Sleeper stat line, pool players
}
The engine's simSeason banks these instead of sampling: a player's points for a finished game are his real points
under the sim's scoring (pts_std + rec x receptions + (pass TD pts - 4) x pass TDs + TE premium - the same formula
the league sim uses), 0 if his team played and he has no stat line. Kill: window.SIM_BANK_PLAYED = false.

Source: api.sleeper.app/v1/stats/nfl/regular/<season>/<week>. A finished week is cached in data/actuals_cache/ and
re-pulled for three days after its last kickoff (stat corrections), then left alone. Called at the end of
refresh_data.py (non-fatal) and runnable alone.
"""
import datetime, json, os, sys, time, urllib.request
HERE = os.path.dirname(os.path.abspath(__file__)); DATA = os.path.join(HERE, "data")
CACHE = os.path.join(DATA, "actuals_cache"); OUT = os.path.join(DATA, "sim_actuals_2026.js")
SEASON = 2026; FINAL_HOURS = 5; CORRECTION_DAYS = 3
FIELDS = ("pts_std", "rec", "pass_td", "pass_yd", "rush_yd", "rush_td", "rec_yd", "rec_td")
ALIAS = {"ARZ": "ARI", "WSH": "WAS", "JAC": "JAX", "LA": "LAR", "OAK": "LV"}
def tm(t): return ALIAS.get(t, t)
def _dt(iso): return datetime.datetime.fromisoformat(iso.replace("Z", "+00:00"))

def pool_sids():
    """Sleeper ids the engine projects (data/sleeper_players.js) - None = keep everyone"""
    try:
        raw = open(os.path.join(DATA, "sleeper_players.js"), encoding="utf-8").read()
        d = json.loads(raw[raw.index("{", raw.index("window.SIM_SLEEPER")):raw.rindex("}") + 1])
        return {str(p["sid"]) for p in d.get("players", []) if p.get("sid")}
    except Exception as e:
        print(f"  WARN pool ids unreadable ({e}) - keeping every player with a stat line"); return None

def fetch_week(wk):
    req = urllib.request.Request(f"https://api.sleeper.app/v1/stats/nfl/regular/{SEASON}/{wk}", headers={"User-Agent": "simlab-refresh"})
    with urllib.request.urlopen(req, timeout=60) as r: return json.load(r)

def build(now=None, quiet=False):
    now = now or datetime.datetime.now(datetime.timezone.utc)
    kicks = json.load(open(os.path.join(DATA, "kickoffs_2026.json"), encoding="utf-8"))
    os.makedirs(CACHE, exist_ok=True)
    pool = pool_sids(); done = {}; weeks = {}
    for wk in range(1, 19):
        k = kicks.get(str(wk)) or {}
        fin = sorted(tm(t) for t, iso in k.items() if now >= _dt(iso) + datetime.timedelta(hours=FINAL_HOURS))
        if not fin: continue
        last = max(_dt(iso) for iso in k.values())
        settled = len(fin) == len(k) and now >= last + datetime.timedelta(days=CORRECTION_DAYS)
        cp = os.path.join(CACHE, f"sleeper_stats_{SEASON}_{wk}.json"); stats = None
        if settled and os.path.exists(cp) and os.path.getmtime(cp) >= (last + datetime.timedelta(days=CORRECTION_DAYS)).timestamp():
            stats = json.load(open(cp, encoding="utf-8"))
        if stats is None:
            try:
                stats = fetch_week(wk); json.dump(stats, open(cp, "w", encoding="utf-8"), separators=(",", ":"))
            except Exception as e:
                if os.path.exists(cp): stats = json.load(open(cp, encoding="utf-8")); print(f"  WARN week {wk} stats pull failed ({e}) - using the cached copy")
                else: print(f"  WARN week {wk} stats pull failed ({e}) - week not banked"); continue
        rows = {}
        for sid, s in stats.items():
            if not isinstance(s, dict) or s.get("pts_std") is None: continue
            if pool is not None and sid not in pool and not (sid.isalpha() and len(sid) <= 3): continue      # team defenses are keyed by abbreviation
            rows[tm(sid) if sid.isalpha() else sid] = [round(float(s.get(f) or 0), 2) for f in FIELDS]
        done[str(wk)] = fin; weeks[str(wk)] = rows
    payload = {"updated": now.strftime("%Y-%m-%dT%H:%MZ"), "season": SEASON, "fields": list(FIELDS), "done": done, "weeks": weeks}
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_actuals.py - real results for games already played (the season sim banks these instead of sampling)\n")
        f.write("// done[wk] = teams whose game is final; weeks[wk][sleeper id] = [pts_std, rec, pass_td, pass_yd, rush_yd, rush_td, rec_yd, rec_td]\n")
        f.write("window.SIM_ACTUALS_2026 = " + json.dumps(payload, separators=(",", ":")) + ";\n")
    if not quiet:
        print("wrapped sim_actuals_2026.js  (" + ", ".join(f"wk {w}: {len(done[w])} teams final / {len(weeks[w])} stat lines" for w in sorted(done, key=int)) + ")")
    return payload

if __name__ == "__main__":
    build()
