#!/usr/bin/env python3
"""
EXPORT THE LEARNED SEASON PRIOR FOR THE ENGINE (2026-09-16) -> data/ridge_prior.js (window.SIM_RIDGE_PRIOR).

backtest_season_long.py: ridge basic beats Clay's season sheet; backtest_learned_prior_weekly.py: mixed 50/50 with
the shadow's hand prior it beats the weekly shadow LOYO -0.5% (6/7) and forward -0.48% (4/5), week 1 -1.35% (5/5).
The live feature set drops `mover` (last-year team is not on the live player record; coefficient < 0.7 everywhere).
Per position, fit on all 2019-25 player-seasons (games-weighted, alpha 10): feature list, training medians (impute),
missing-indicator columns (features > 2% missing), standardization mean / sd, coefficients, intercept. The engine
rebuilds the same vector live (engine.js ridgePrior). Also prints the LOYO check with and without `mover`.
"""
import json, os, sys, time
import numpy as np
from sklearn.linear_model import Ridge

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import backtest_season_long as SL
from backtest_target_area import mse

LIVE = [f for f in SL.BASIC if f != "mover"] + ["jm"]   # v2.16: JM prospect score (backtest 09-16: weighted top 150 -1.2% LOYO 6/7, -0.9% fwd 4/5)
ALPHA = 10.0


def main():
    T = SL.build_table()
    w = T.games.values.astype(float)
    for lab, fs in (("BASIC (with mover)", SL.BASIC), ("LIVE (no mover)", LIVE)):
        pr = SL.loyo(T, fs, "ridge", ALPHA); e = SL.wmse(pr, T.ppg.values, w); ec = SL.wmse(T.clay.values, T.ppg.values, w)
        print(f"  {lab:20s} LOYO games-weighted MSE {e:.3f} vs Clay {ec:.3f} ({(e/ec-1)*100:+.2f}%)")
    out = {"updated": time.strftime("%Y-%m-%d %H:%M"), "alpha": ALPHA, "feats": LIVE, "models": {}, "src": "build_ridge_prior.py: ridge basic fit 2019-25 per position, games-weighted; half-PPR PPG"}
    for ps in SL.POS4:
        m = (T.pos == ps).values; X = T.loc[m, LIVE].astype(float).values; y = T.ppg.values[m]; ww = w[m]
        med = np.nanmedian(X, axis=0); med = np.where(np.isnan(med), 0, med)
        miss = [j for j in range(X.shape[1]) if np.isnan(X[:, j]).mean() > 0.02]
        Xf = np.where(np.isnan(X), med, X); ind = np.isnan(X[:, miss]).astype(float) if miss else np.zeros((len(X), 0))
        A = np.column_stack([Xf, ind]); mu, sd = A.mean(0), A.std(0); sd[sd == 0] = 1
        mdl = Ridge(alpha=ALPHA).fit((A - mu) / sd, y, sample_weight=ww)
        out["models"][ps] = {"n": int(m.sum()), "med": [round(float(v), 4) for v in med], "miss": miss, "mu": [round(float(v), 5) for v in mu], "sd": [round(float(v), 5) for v in sd],
                             "coef": [round(float(v), 5) for v in mdl.coef_], "b": round(float(mdl.intercept_), 5)}
        pred = np.maximum(0.5, mdl.predict((A - mu) / sd))
        print(f"  {ps}: n {m.sum()} in-sample MSE {SL.wmse(pred, y, ww):.3f} | missing-indicator cols {[LIVE[j] for j in miss]} | mean pred {pred.mean():.2f} vs actual {np.average(y, weights=ww):.2f}")
    with open(os.path.join(HERE, "data", "ridge_prior.js"), "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_ridge_prior.py - learned season prior (ridge basic) for the Clay-free shadow, half-PPR PPG\nwindow.SIM_RIDGE_PRIOR = " + json.dumps(out) + ";\n")
    print("wrote data/ridge_prior.js")


if __name__ == "__main__":
    main()
