// outliers_week.js [week] - where the Clay-free shadow (ncMean) disagrees most with the live Clay-based mean this week.
// Run: node outliers_week.js 2   -> prints both directions + per-position summary, writes data/outliers_w{N}.json
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
global.window = global;
const src = fs.readFileSync(path.join(__dirname, 'export_site_proj.js'), 'utf8');
const files = src.match(/\[\s*((?:'data\/[^']+',\s*)+'overrides\.js',\s*'engine\.js')\s*\]/)[1].match(/'([^']+)'/g).map(s => s.slice(1, -1));
files.forEach(f => vm.runInThisContext(fs.readFileSync(path.join(__dirname, f), 'utf8'), { filename: f }));
const E = global.SimEngine, WK = parseInt(process.argv[2] || '2', 10), sc = E.PRESETS.half;
const schedule = E.buildSchedule(), players = E.buildPlayers(schedule);
E.applyInSeasonInjuries(players, WK, { active: true });
const rows = [];
players.list.forEach(p => {
  if (!/^(QB|RB|WR|TE)$/.test(p.pos)) return;
  const wp = E.weeklyProjection(p, WK, sc, schedule); if (!wp || wp.ncMean == null) return;
  const live = wp.mean, nc = wp.ncMean; if (live < 4 && nc < 4) return;
  rows.push({ n: p.name, pos: p.pos, tm: p.tm, live: +live.toFixed(2), js: wp.jsMean == null ? null : +wp.jsMean.toFixed(2), nc: +nc.toFixed(2), diff: +(nc - live).toFixed(2), src: wp.ncSrc, adp: p.adp, exp: p.exp });
});
const fmt = r => `${r.n.padEnd(22)} ${r.pos} ${String(r.tm).padEnd(4)} live ${r.live.toFixed(1).padStart(5)}  shadow ${r.nc.toFixed(1).padStart(5)}  diff ${(r.diff >= 0 ? '+' : '') + r.diff.toFixed(1).padStart(5)}  (${r.src})`;
console.log(`week ${WK}: ${rows.length} skill players with a shadow number\n=== SHADOW HIGHER than live (top 15) ===`);
rows.filter(r => r.diff > 0).sort((a, b) => b.diff - a.diff).slice(0, 15).forEach(r => console.log('  ' + fmt(r)));
console.log('\n=== SHADOW LOWER than live (top 15) ===');
rows.filter(r => r.diff < 0).sort((a, b) => a.diff - b.diff).slice(0, 15).forEach(r => console.log('  ' + fmt(r)));
['QB', 'RB', 'WR', 'TE'].forEach(ps => {
  const pr = rows.filter(r => r.pos === ps); const mean = pr.reduce((s, r) => s + r.diff, 0) / pr.length; const mad = pr.reduce((s, r) => s + Math.abs(r.diff), 0) / pr.length;
  console.log(`${ps}: n ${pr.length}, shadow - live avg ${mean >= 0 ? '+' : ''}${mean.toFixed(2)}, mean |diff| ${mad.toFixed(2)}, |diff| >= 3: ${pr.filter(r => Math.abs(r.diff) >= 3).length}`);
});
const out = { week: WK, updated: new Date().toISOString(), rows: rows.sort((a, b) => Math.abs(b.diff) - Math.abs(a.diff)) };
fs.writeFileSync(path.join(__dirname, 'data', `outliers_w${WK}.json`), JSON.stringify(out));
fs.writeFileSync(path.join(__dirname, 'data', 'outliers_week.js'), '// AUTO-GENERATED by outliers_week.js - Clay-free shadow vs live mean, biggest disagreements this week\nwindow.SIM_OUTLIERS = ' + JSON.stringify(out) + ';\n');
