#!/usr/bin/env python3
"""
Sim Lab data refresh — copies the latest data out of the MFF site repo and the
Sleeper extension into sim_lab/data/. Run whenever the site data refreshes
(the 9am consensus pull / betting pull already keep the sources fresh).

Sources:
  MFF repo  data/mike_clay_projections.js  -> data/mike_clay_projections.js
  MFF repo  data/player_weekly_sigma.js    -> data/player_weekly_sigma.js
  MFF repo  data/betting_lines_2026.js     -> data/betting_lines_2026.js
  sleeper-extension/data/players.json      -> data/sleeper_players.js  (wrapped as window.SIM_SLEEPER)

Usage:  python refresh_data.py
"""
import json, os, shutil, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = r"E:\MyFantasyFootball\MyFantasyFootball Files"
OUT  = os.path.join(HERE, "data")
os.makedirs(OUT, exist_ok=True)

COPIES = [
    (os.path.join(REPO, "data", "mike_clay_projections.js"), "mike_clay_projections.js"),
    (os.path.join(REPO, "data", "player_weekly_sigma.js"),   "player_weekly_sigma.js"),
    (os.path.join(REPO, "data", "betting_lines_2026.js"),    "betting_lines_2026.js"),
    (os.path.join(REPO, "data", "clay_team_grades_2026.js"), "clay_team_grades_2026.js"),
    # Yahoo league import: the site's HTML-page normalizer (itself a synced
    # copy of yahoo-extension/yahoo-normalize.js) — parses standings + rosters
    (os.path.join(REPO, "yahoo_normalize.js"),               "yahoo_normalize.js"),
]

for src, name in COPIES:
    shutil.copyfile(src, os.path.join(OUT, name))
    print(f"copied {name}  ({os.path.getsize(src)//1024} KB)")

# Practice reports (scripts/pull_practice_reports.py -> data/practice_2026.json)
# and ESPN depth charts (scripts/pull_depth_charts.py -> data/depth_charts_2026.json)
# for the engine's in-season injury layer (2026-09-09): Questionable + DNP
# docks, NFL Out/Doubtful when Sleeper lags, depth-rank-weighted vacated
# share. Missing repo file -> empty object -> engine falls back to the
# Sleeper-only behaviour.
for jname, out_name, var in (("practice_2026.json", "sim_practice.js", "SIM_PRACTICE_2026"),
                             ("depth_charts_2026.json", "sim_depth.js", "SIM_DEPTH_2026"),
                             # beat-report feed (cloud camp-news routine, in-season items tagged riser/faller/injury/role)
                             # -> REPORTS shadow flag on the NOTES sheet + lock rows (Jack 2026-09-15)
                             ("camp_news_2026.json", "sim_news.js", "SIM_NEWS_2026")):
    payload = {}
    try:
        payload = json.load(open(os.path.join(REPO, "data", jname), encoding="utf-8"))
    except Exception as e_j:
        print(f"WARN {jname} unavailable ({e_j}) — {var} empty")
    with open(os.path.join(OUT, out_name), "w", encoding="utf-8") as f:
        f.write(f"// AUTO-GENERATED by refresh_data.py from data/{jname}\n")
        f.write(f"window.{var} = ")
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")
    n = len((payload.get("players") or payload.get("teams") or payload.get("items") or {}))
    print(f"wrapped {out_name}  ({n} entries, {str(payload.get('updated', ''))[:16]})")

# players.json (sleeper ids + ADP) -> JS global so file:// pages can load it
pj = os.path.join(REPO, "sleeper-extension", "data", "players.json")
with open(pj, encoding="utf-8") as f:
    data = json.load(f)
with open(os.path.join(OUT, "sleeper_players.js"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by refresh_data.py from sleeper-extension/data/players.json\n")
    f.write("window.SIM_SLEEPER = ")
    json.dump(data, f, separators=(",", ":"))
    f.write(";\n")
print(f"wrapped sleeper_players.js  ({len(data.get('players', []))} players, exported {data.get('exported_at','?')})")

# 2026 snap counts, trimmed from the site's full SNAP_COUNTS history (415KB ->
# only the current season). Empty until the season starts; the engine's snap
# usage layer self-activates once weeks appear here. Re-run after each
# pull_snap_counts.py refresh during the season.
try:
    sc_path = os.path.join(REPO, "data", "snap_counts.js")
    raw = open(sc_path, encoding="utf-8").read()
    full, _end = json.JSONDecoder().raw_decode(raw, raw.index("{"))
    season = {name: yrs["2026"] for name, yrs in full.items() if "2026" in yrs}
    with open(os.path.join(OUT, "sim_snaps.js"), "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by refresh_data.py from data/snap_counts.js (2026 only)\n")
        f.write("// {player: {s: season snap %, w: {week: snap %}}}\n")
        f.write("window.SIM_SNAPS_2026 = ")
        json.dump(season, f, separators=(",", ":"))
        f.write(";\n")
    print(f"wrapped sim_snaps.js  ({len(season)} players with 2026 snaps)")
except Exception as e:
    print(f"WARN sim_snaps.js skipped ({e})")

# 2026 in-season results for the JS Weekly model: per-player season-to-date
# per-game averages (fpts + stat mix for rescoring) and per-defense fantasy
# points ALLOWED per game by position. Empty preseason — JS Weekly equals the
# Clay model until real games exist. Re-run after each fetch_weekly_stats.py.
try:
    import re as _re
    def _norm(s):
        s = s.lower().replace(".", "").replace("'", "").replace("-", " ")
        s = _re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", s)
        return _re.sub(r"\s+", " ", s).strip()
    _ALIAS = {"ARZ":"ARI","WSH":"WAS","JAC":"JAX","LA":"LAR","OAK":"LV","SD":"LAC","STL":"LAR","HST":"HOU","BLT":"BAL","CLV":"CLE"}
    wsa = open(os.path.join(REPO, "data", "weekly_stats_active.js"), encoding="utf-8").read()
    wall, _ = json.JSONDecoder().raw_decode(wsa, wsa.index("{"))
    STATS = ["rec", "tgt", "ry", "rcy", "rtd", "rctd", "py", "ptd"]
    players26, fpa, defgames = {}, {}, {}
    l8only = {}
    for name, rec in wall.items():
        wks = (rec.get("seasons") or {}).get("2026") or []
        pos = rec.get("pos")
        rows = [w for w in wks if isinstance(w.get("fpts"), (int, float))]
        if not rows:
            # no 2026 game yet: still record the last-8 prior (2024-25 tail) for the shadow base
            tail = []
            for yr_, wl in (rec.get("seasons") or {}).items():
                if str(yr_).isdigit() and 2024 <= int(yr_) <= 2025:
                    for w in wl:
                        if isinstance(w.get("fpts"), (int, float)) and str(w.get("wk", "")).isdigit():
                            tail.append((int(yr_), int(w["wk"]), float(w["fpts"])))
            tail.sort(); tail = tail[-8:]
            if tail:
                l8only[_norm(name)] = {"g": 0, "l8": round(sum(x[2] for x in tail) / len(tail), 2), "l8g": len(tail)}
            continue
        g = len(rows)
        pg = {k: round(sum(w.get(k) or 0 for w in rows) / g, 2) for k in STATS}
        # wks = weeks with a stat row: the engine's rate-track teammate guard
        # reads it to tell "teammate sat this week" from "teammate played".
        wks_played = sorted({int(w["wk"]) for w in rows if str(w.get("wk", "")).isdigit()})
        # last-8-played-games PPG across seasons (recency prior for the Clay-free shadow base;
        # Jack 2026-09-15: a player "great over the last 7ish games" must not be averaged away)
        allrows = []
        for yr_, wl in (rec.get("seasons") or {}).items():
            if not str(yr_).isdigit() or int(yr_) < 2024:
                continue
            for w in wl:
                if isinstance(w.get("fpts"), (int, float)) and str(w.get("wk", "")).isdigit():
                    allrows.append((int(yr_), int(w["wk"]), float(w["fpts"])))
        allrows.sort()
        l8 = allrows[-8:]
        players26[_norm(name)] = {"g": g, "ppg": round(sum(w["fpts"] for w in rows) / g, 2), "pg": pg, "wks": wks_played,
                                  "l8": round(sum(x[2] for x in l8) / len(l8), 2) if l8 else None, "l8g": len(l8)}
        for w in rows:
            opp = _ALIAS.get(w.get("opp") or "", w.get("opp") or "")
            if not opp or not pos:
                continue
            fpa.setdefault(opp, {}).setdefault(pos, 0.0)
            fpa[opp][pos] += w["fpts"]
            defgames.setdefault(opp, set()).add(w.get("wk"))
    lg = {}
    for opp in fpa:
        gcount = max(1, len(defgames.get(opp, [])))
        fpa[opp] = {p: round(v / gcount, 2) for p, v in fpa[opp].items()}
        fpa[opp]["_g"] = gcount
    for posk in ("QB", "RB", "WR", "TE"):
        vals = [fpa[o][posk] for o in fpa if posk in fpa[o]]
        if vals:
            lg[posk] = round(sum(vals) / len(vals), 2)
    # 2026-09-14: prefer the COMPLETE-league FPA table (repo data/fpa_2026.js,
    # every Sleeper QB/RB/WR/TE in FINAL games, built by pull_postgame_stats.py)
    # over the board-only sum above. Untracked backups otherwise read as
    # shutouts (W1: PIT 0.0 QB allowed -- Cooper Rush isn't on the board).
    fpa_src = "board-only (weekly_stats_active)"
    try:
        fp_path = os.path.join(REPO, "data", "fpa_2026.js")
        if os.path.exists(fp_path):
            ftxt = open(fp_path, encoding="utf-8").read()
            fobj, _ = json.JSONDecoder().raw_decode(ftxt, ftxt.index("{"))
            fweeks = fobj.get("weeks") or {}
            if fweeks:
                tot, gcnt = {}, {}
                for wk, teams in fweeks.items():
                    for d, rec in teams.items():
                        d2 = _ALIAS.get(d, d)
                        for posk in ("QB", "RB", "WR", "TE"):
                            v = rec.get(posk)
                            if isinstance(v, (int, float)):
                                tot.setdefault(d2, {}).setdefault(posk, 0.0)
                                tot[d2][posk] += v
                        gcnt.setdefault(d2, set()).add(wk)
                fpa = {d: {p: round(v / len(gcnt[d]), 2) for p, v in ps.items()} for d, ps in tot.items()}
                for d in fpa:
                    fpa[d]["_g"] = len(gcnt[d])
                lg = {}
                for posk in ("QB", "RB", "WR", "TE"):
                    vals = [fpa[o][posk] for o in fpa if posk in fpa[o]]
                    if vals:
                        lg[posk] = round(sum(vals) / len(vals), 2)
                fpa_src = "fpa_2026.js (complete league)"
    except Exception as e:
        print(f"WARN complete-league FPA skipped ({e}) - board-only FPA kept")
    with open(os.path.join(OUT, "sim_2026.js"), "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by refresh_data.py from data/weekly_stats_active.js (2026 season only)\n")
        f.write("// players: {normName: {g, ppg (half-PPR), pg: per-game stat mix}}\n")
        f.write("// fpa: {DEF: {pos: fantasy pts allowed/gm, _g: games}}; lgFpa: league avg by pos\n")
        f.write("window.SIM_2026 = ")
        for _k, _v in l8only.items():
            players26.setdefault(_k, _v)
        json.dump({"players": players26, "fpa": fpa, "lgFpa": lg}, f, separators=(",", ":"))
        f.write(";\n")
    print(f"wrapped sim_2026.js  ({len(players26)} players with 2026 games, {len(fpa)} defenses; FPA {fpa_src})")
except Exception as e:
    print(f"WARN sim_2026.js skipped ({e})")

# Sleeper player metadata (years_exp = 0 marks TRUE rookies; a 2nd-year player
# with a tiny sample is not a rookie). One ~5MB pull per refresh, trimmed to
# our player pool before writing.
try:
    import urllib.request
    sids = {str(p.get("sid")) for p in data.get("players", []) if p.get("sid")}
    req = urllib.request.Request("https://api.sleeper.app/v1/players/nfl",
                                 headers={"User-Agent": "simlab-refresh"})
    with urllib.request.urlopen(req, timeout=60) as r:
        allp = json.load(r)
    meta = {}
    for sid, rec in allp.items():
        if sid in sids and isinstance(rec, dict):
            meta[sid] = {"exp": rec.get("years_exp"), "inj": rec.get("injury_status") or "",
                         "st": rec.get("status") or ""}
    # Elite shadow-CB status (backtest_cb_shadow.py): resolve each name in
    # overrides.js ELITE_CBS_2026 to current team + injury/roster status from
    # the same dump. Engine docks opposing WRs x0.96 while the CB is available.
    import re as _rcb
    def _cbnorm(n):
        n = n.lower().replace(".", "").replace("'", "").replace("-", " ")
        n = _rcb.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", n)
        return _rcb.sub(r"\s+", " ", n).strip()
    cb_status = {}
    ov = open(os.path.join(HERE, "overrides.js"), encoding="utf-8").read()
    m = _rcb.search(r"ELITE_CBS_2026\s*=\s*\[(.*?)\]", ov, _rcb.S)
    if m:
        names = _rcb.findall(r"'([^']+)'", m.group(1))
        want = {_cbnorm(n): n for n in names}
        for rec in allp.values():
            if not isinstance(rec, dict) or rec.get("position") not in ("CB", "DB"):
                continue
            nm = want.get(_cbnorm(rec.get("full_name") or ""))
            if nm and (rec.get("team") or nm not in cb_status):
                cb_status[nm] = {"tm": rec.get("team") or "",
                                 "inj": rec.get("injury_status") or "",
                                 "st": rec.get("status") or ""}
        missing = [n for n in names if n not in cb_status]
        if missing:
            print(f"WARN elite CBs not found in Sleeper dump: {missing}")
    with open(os.path.join(OUT, "sleeper_meta.js"), "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by refresh_data.py from api.sleeper.app/v1/players/nfl\n")
        f.write("// {sid: {exp: years_exp, inj: injury_status, st: roster_status}}\n")
        f.write("window.SIM_SLEEPER_META = ")
        json.dump(meta, f, separators=(",", ":"))
        f.write(";\n")
        # Sleeper's OWN weekly projection (repo data/weekly_projections.json, 'h' = Sleeper half-PPR;
        # missing/0 = Sleeper has ruled him out). The engine zeroes a Sleeper "Out" flag only when
        # this is 0 too (Jack 2026-09-15: "not to 0 anyone out before they are out or at least
        # doubtful ... check who sleeper has 0s for"); a flag with a live projection is a stale
        # game-day inactive or a premature tag -> x0.75 'out-unconfirmed' instead.
        sw = {"week": None, "p": {}}
        try:
            wp = json.load(open(os.path.join(REPO, "data", "weekly_projections.json"), encoding="utf-8"))
            sw["week"] = wp.get("week")
            for nm, rec in (wp.get("players") or {}).items():
                sw["p"][_cbnorm(nm)] = rec.get("h") if isinstance(rec, dict) else None
        except Exception as e:  # noqa: BLE001
            print(f"WARN weekly_projections.json unreadable ({e}) - SIM_SLEEPER_WEEKLY empty")
        f.write("// Sleeper's own current-week projection per player (half-PPR; absent = Sleeper has him at 0)\n")
        f.write("window.SIM_SLEEPER_WEEKLY = ")
        json.dump(sw, f, separators=(",", ":"))
        f.write(";\n")
        f.write("// elite shadow-CB availability (ELITE_CBS_2026 in overrides.js)\n")
        f.write("window.SIM_CB_STATUS = ")
        json.dump(cb_status, f, separators=(",", ":"))
        f.write(";\n")
        # WR slot rates (most recent PFF receiving season, >=100 routes) —
        # graduates the shadow-CB dock: slot receivers are shielded (elite
        # corners play outside; research_cb_wr_side.py). Unknown = mid dock.
        wr_slot = {}
        try:
            import csv as _csv
            pffdir = r"E:\MyFantasyFootball\pbp_cache\pff"
            yrs = sorted(int(f2[14:18]) for f2 in os.listdir(pffdir)
                         if _rcb.match(r"pff_receiving_\d{4}\.csv$", f2))
            for y in yrs[-2:]:  # older season first; newest overwrites
                with open(os.path.join(pffdir, f"pff_receiving_{y}.csv"), encoding="utf-8") as fh:
                    for row in _csv.DictReader(fh):
                        try:
                            if row["position"] == "WR" and float(row["routes"]) >= 100:
                                wr_slot[_cbnorm(row["player"])] = round(float(row["slot_rate"]), 1)
                        except (KeyError, ValueError):
                            pass
        except Exception as e2:
            print(f"WARN wr slot rates skipped ({e2}) — dock falls back to flat")
        f.write("// WR slot rates (latest PFF season) for the graduated CB dock\n")
        f.write("window.SIM_WR_SLOT = ")
        json.dump(wr_slot, f, separators=(",", ":"))
        f.write(";\n")
        # CB1-out boost layer (backtest_cb1_boost.py): each team's CB1 + is
        # he out. In-season CB1 = top defensive-snap CB from the nflverse
        # 2026 snap parquet (re-downloaded when stale; 404 = preseason);
        # before 2026 data exists, 2025 snap profiles mapped through each
        # player's CURRENT Sleeper team. Status from the same Sleeper dump.
        cb1_map = {}
        try:
            cache_dir = r"E:\MyFantasyFootball\pbp_cache"
            pq26 = os.path.join(cache_dir, "snap_counts_2026.parquet")
            try:
                stale = (not os.path.exists(pq26) or
                         __import__("time").time() - os.path.getmtime(pq26) > 20 * 3600)
                if stale:
                    urllib.request.urlretrieve(
                        "https://github.com/nflverse/nflverse-data/releases/download/snap_counts/snap_counts_2026.parquet",
                        pq26)
            except Exception:
                pass  # preseason 404 / offline — fall through to 2025
            import pandas as _pdcb
            TEAM_FIX = {"WSH": "WAS", "LA": "LAR", "OAK": "LV", "SD": "LAC",
                        "JAC": "JAX", "ARZ": "ARI", "BLT": "BAL", "CLV": "CLE", "HST": "HOU"}
            # Sleeper lookup: exact norm first, then first-3-chars+lastname
            # (PFR 'Patrick Surtain II' vs Sleeper 'Pat Surtain'); ambiguous
            # short keys are dropped.
            sl_exact, sl_short = {}, {}
            for rec in allp.values():
                if not isinstance(rec, dict) or rec.get("position") not in ("CB", "DB"):
                    continue
                nmn = _cbnorm(rec.get("full_name") or "")
                if not nmn:
                    continue
                sl_exact.setdefault(nmn, rec)
                parts = nmn.split()
                sk = parts[0][:3] + " " + parts[-1]
                sl_short[sk] = None if sk in sl_short else rec
            def sleeper_cb(pfr_name):
                nmn = _cbnorm(pfr_name)
                r = sl_exact.get(nmn)
                if r is None:
                    parts = nmn.split()
                    r = sl_short.get(parts[0][:3] + " " + parts[-1]) or None
                return r
            def cb_rows(pq):
                df = _pdcb.read_parquet(pq, columns=["week", "game_type", "player",
                                                     "position", "team", "defense_pct"])
                return df[(df.game_type == "REG") & (df.position == "CB") & (df.defense_pct >= 0.6)]
            def is_out(s):
                return (s.get("status") != "Active" or
                        (s.get("injury_status") or "").startswith(("Out", "Doubtful")))
            use26 = False
            if os.path.exists(pq26):
                df26 = cb_rows(pq26)
                by_tm = {}
                for (nm, t), rows in df26.groupby(["player", "team"]):
                    tm = TEAM_FIX.get(t, t)
                    key = (len(rows), float(rows.defense_pct.mean()))
                    if tm not in by_tm or key > by_tm[tm][0]:
                        by_tm[tm] = (key, nm)
                if len(by_tm) >= 20:   # real in-season sample
                    use26 = True
                    for tm, (_, nm) in by_tm.items():
                        s = sleeper_cb(nm)
                        if s is None:
                            print(f"WARN CB1 {nm} ({tm}): no Sleeper match — no boost")
                            continue
                        cb1_map[tm] = {"name": nm, "out": is_out(s), "src": "2026"}
            if not use26:
                # 2025 profiles (games summed ACROSS team stints — trades) ->
                # each player's CURRENT Sleeper team
                df25 = cb_rows(os.path.join(cache_dir, "snap_counts_2025.parquet"))
                best = {}
                for nm, rows in df25.groupby("player"):
                    if len(rows) < 8:
                        continue
                    s = sleeper_cb(nm)
                    cur = s.get("team") if s else None
                    if not cur:
                        continue
                    key = (len(rows), float(rows.defense_pct.mean()))
                    if cur not in best or key > best[cur][0]:
                        best[cur] = (key, {"name": nm, "out": is_out(s), "src": "2025"})
                cb1_map = {tm: v[1] for tm, v in best.items()}
        except Exception as e3:
            print(f"WARN CB1 map skipped ({e3}) — boost layer inert")
        f.write("// CB1-out boost: each team's top-snap CB + current availability\n")
        f.write("window.SIM_CB1_2026 = ")
        json.dump(cb1_map, f, separators=(",", ":"))
        f.write(";\n")
        # OL-out dock (backtest_ol_out.py): how many of a team's starting-
        # five linemen are currently unavailable. Docks the team's OWN
        # skill players (RB 1-missing x0.98 / 2+ x0.95; QB/WR/TE 2+ x0.97).
        # Starting five: 2026 top-snap C/G/T in-season; 2025 profiles ->
        # current Sleeper teams preseason. Teams whose five can't fully
        # resolve are omitted (engine treats absent = no adjustment).
        ol_map = {}
        try:
            sl_ol_exact, sl_ol_short = {}, {}
            for rec in allp.values():
                if not isinstance(rec, dict) or rec.get("position") not in ("OL", "T", "G", "C", "OT"):
                    continue
                nmn = _cbnorm(rec.get("full_name") or "")
                if not nmn:
                    continue
                prev = sl_ol_exact.get(nmn)
                if prev is None or (not prev.get("team") and rec.get("team")):
                    sl_ol_exact[nmn] = rec
                parts = nmn.split()
                sk = parts[0][:3] + " " + parts[-1]
                sl_ol_short[sk] = None if sk in sl_ol_short else rec
            def sleeper_ol(nm):
                nmn = _cbnorm(nm)
                r = sl_ol_exact.get(nmn)
                if r is None:
                    parts = nmn.split()
                    r = sl_ol_short.get(parts[0][:3] + " " + parts[-1]) or None
                return r
            def ol_rows(pq):
                df = _pdcb.read_parquet(pq, columns=["week", "game_type", "player",
                                                     "position", "team", "offense_pct"])
                return df[(df.game_type == "REG") & (df.position.isin(["C", "G", "T"]))
                          & (df.offense_pct >= 0.6)]
            fives = {}
            use26_ol = False
            if os.path.exists(pq26):
                by_tm = {}
                for (nm, t), rows in ol_rows(pq26).groupby(["player", "team"]):
                    tm = TEAM_FIX.get(t, t)
                    by_tm.setdefault(tm, []).append((len(rows), float(rows.offense_pct.mean()), nm))
                if len(by_tm) >= 20:
                    use26_ol = True
                    for tm, lst in by_tm.items():
                        lst.sort(reverse=True)
                        if len(lst) >= 5:
                            fives[tm] = [nm for _, _, nm in lst[:5]]
            if not use26_ol:
                by_cur = {}
                for nm, rows in ol_rows(os.path.join(cache_dir, "snap_counts_2025.parquet")).groupby("player"):
                    if len(rows) < 6:
                        continue
                    s = sleeper_ol(nm)
                    cur = s.get("team") if s else None
                    if not cur:
                        continue
                    by_cur.setdefault(cur, []).append((len(rows), float(rows.offense_pct.mean()), nm))
                for tm, lst in by_cur.items():
                    lst.sort(reverse=True)
                    if len(lst) >= 5:
                        fives[tm] = [nm for _, _, nm in lst[:5]]
            for tm, names in fives.items():
                out_n, known = 0, True
                for nm in names:
                    s = sleeper_ol(nm)
                    if s is None:
                        known = False
                        break
                    if is_out(s):
                        out_n += 1
                if known:
                    ol_map[tm] = out_n
        except Exception as e4:
            print(f"WARN OL map skipped ({e4}) — OL dock inert")
        f.write("// OL-out dock: count of each team's starting-five OL currently unavailable\n")
        f.write("window.SIM_OL_2026 = ")
        json.dump(ol_map, f, separators=(",", ":"))
        f.write(";\n")
    rookies = sum(1 for m in meta.values() if m["exp"] == 0)
    print(f"wrapped sleeper_meta.js  ({len(meta)} players, {rookies} true rookies, {len(cb_status)} elite CBs)")
except Exception as e:
    print(f"WARN sleeper_meta.js skipped ({e}) — engine falls back to age heuristic")

# Weather forecasts for the sims (backtest_weather.py: wind docks QB/WR/TE
# at >=10/>=15 mph and K at >=10 — effects survive Vegas adjustment AND
# week-of-season control; RB immune; no dome boost, that's a venue-mix
# composition artifact). Open-Meteo (free, no key), one request per OUTDOOR
# stadium, hourly wind/temp over the 16-day horizon, sampled at each
# kickoff (mean of kickoff hour +3h) from data/kickoffs_2026.json.
# Games beyond the horizon simply have no entry -> engine no-op.
try:
    import urllib.request as _uw
    STADIUMS = {  # outdoor only; retractables/domes get no entry = no dock
        "BUF": (42.774, -78.787), "MIA": (25.958, -80.239), "NE": (42.091, -71.264),
        "NYJ": (40.813, -74.074), "NYG": (40.813, -74.074), "BAL": (39.278, -76.623),
        "CIN": (39.095, -84.516), "CLE": (41.506, -81.699), "PIT": (40.447, -80.016),
        "JAX": (30.324, -81.637), "TEN": (36.166, -86.771), "DEN": (39.744, -105.020),
        "KC": (39.049, -94.484), "SEA": (47.595, -122.332), "SF": (37.403, -121.970),
        "GB": (44.501, -88.062), "CHI": (41.862, -87.617), "PHI": (39.901, -75.168),
        "WAS": (38.908, -76.864), "CAR": (35.226, -80.853), "TB": (27.976, -82.503),
    }
    kicks = json.load(open(os.path.join(OUT, "kickoffs_2026.json"), encoding="utf-8"))
    now = datetime.datetime.now(datetime.timezone.utc)
    horizon = now + datetime.timedelta(days=16)
    weather = {}
    wx_src = "open-meteo"
    # PRIMARY (2026-09-09): the site's own feed, data/weather_2026.json
    # (scripts/pull_weather.py — ESPN roof + Open-Meteo via `requests`,
    # refreshed by the 9am job and every pre-kickoff export run BEFORE this
    # script). It already resolves indoor/retractable-closed per game and
    # carries gusts + precip. The urllib Open-Meteo path below stays as the
    # fallback — it hit an SSL "certificate has expired" failure on 09-09
    # that was swallowed per stadium and shipped an EMPTY weather file
    # (weather layer silently inert) until this was caught.
    try:
        _site_wx = json.load(open(os.path.join(REPO, "data", "weather_2026.json"), encoding="utf-8"))
        for wk_s, games in (_site_wx.get("weeks") or {}).items():
            for home, g in (games or {}).items():
                if not g or g.get("indoor") or g.get("wind") is None:
                    continue
                home2 = {"WSH": "WAS", "LA": "LAR", "OAK": "LV", "SD": "LAC", "JAC": "JAX"}.get(home, home)
                weather.setdefault(home2, {})[str(wk_s)] = {
                    "wind": g["wind"], "temp": g.get("temp"), "gust": g.get("gust"), "pop": g.get("pop")}
        if weather:
            wx_src = "site weather_2026.json (%s)" % str(_site_wx.get("updated", ""))[:16]
    except Exception as e_wx:
        print(f"  site weather feed unavailable ({e_wx}) — falling back to Open-Meteo")
    fc_cache = {}
    def forecast(lat, lon):
        key = (lat, lon)
        if key not in fc_cache:
            url = ("https://api.open-meteo.com/v1/forecast?latitude=%s&longitude=%s"
                   "&hourly=temperature_2m,wind_speed_10m&temperature_unit=fahrenheit"
                   "&wind_speed_unit=mph&forecast_days=16&timezone=UTC") % (lat, lon)
            with _uw.urlopen(_uw.Request(url, headers={"User-Agent": "simlab"}), timeout=30) as r:
                fc_cache[key] = json.load(r)["hourly"]
        return fc_cache[key]
    wx_err = None
    for wk_s, teams_k in ([] if weather else kicks.items()):
        for team, iso in teams_k.items():
            tm2 = {"WSH": "WAS", "LA": "LAR", "OAK": "LV", "SD": "LAC", "JAC": "JAX"}.get(team, team)
            if tm2 not in STADIUMS:
                continue
            try:
                ko = datetime.datetime.fromisoformat(iso.replace("Z", "+00:00"))
            except ValueError:
                continue
            if not (now - datetime.timedelta(hours=6) <= ko <= horizon):
                continue
            try:
                h = forecast(*STADIUMS[tm2])
                key0 = ko.strftime("%Y-%m-%dT%H:00")
                if key0 not in h["time"]:
                    continue
                i0 = h["time"].index(key0)
                winds = [w for w in h["wind_speed_10m"][i0:i0 + 4] if w is not None]
                temps = [t for t in h["temperature_2m"][i0:i0 + 4] if t is not None]
                if winds:
                    weather.setdefault(tm2, {})[wk_s] = {
                        "wind": round(sum(winds) / len(winds), 1),
                        "temp": round(sum(temps) / len(temps)) if temps else None}
            except Exception as e_st:
                wx_err = e_st  # one stadium failing shouldn't kill the rest — but say so below
    if wx_err is not None:
        print(f"  WARN Open-Meteo fetch failed for at least one stadium ({wx_err})")
    with open(os.path.join(OUT, "sim_weather.js"), "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by refresh_data.py — kickoff-hour wind/temp forecasts\n")
        f.write("// (Open-Meteo, outdoor stadiums, 16-day horizon; keyed home-team -> week)\n")
        f.write("window.SIM_WEATHER_2026 = ")
        json.dump(weather, f, separators=(",", ":"))
        f.write(";\n")
    ngames = sum(len(v) for v in weather.values())
    print(f"wrapped sim_weather.js  ({ngames} outdoor kickoffs in forecast window · {wx_src})")
    if ngames == 0:
        print("  WARN weather layer INERT this run (no outdoor kickoffs resolved)")
except Exception as e:
    print(f"WARN sim_weather.js skipped ({e}) — weather layer inert")
    if not os.path.exists(os.path.join(OUT, "sim_weather.js")):
        with open(os.path.join(OUT, "sim_weather.js"), "w", encoding="utf-8") as f:
            f.write("window.SIM_WEATHER_2026 = {};\n")

# Cache-bust every script tag in index.html (?v=epoch) so browsers always
# pick up new builds — same pattern as the main site.
import re as _re2, time as _time
ix_path = os.path.join(HERE, "index.html")
ix = open(ix_path, encoding="utf-8").read()
v = str(int(_time.time()))
ix2 = _re2.sub(r'src="((?:data/)?[\w./]+\.js)(?:\?v=\d+)?"', lambda m: 'src="%s?v=%s"' % (m.group(1), v), ix)
if ix2 != ix:
    open(ix_path, "w", encoding="utf-8").write(ix2)
print(f"cache-busted index.html scripts (?v={v})")

stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
with open(os.path.join(OUT, "refresh_stamp.js"), "w", encoding="utf-8") as f:
    f.write(f"window.SIM_DATA_REFRESHED = '{stamp}';\n")
print(f"stamped {stamp}")
