#!/usr/bin/env python3
"""Rebuild data/underdog_ids.js from a fresh Underdog rankings CSV export.

Underdog periodically regenerates their player IDs or changes the export
schema (July 2026: added `salary`; Aug 2026: app moved to
app.underdogsports.com, added `playerId` after `id`, dropped the BOM,
LF line endings). When that happens, rankings exported from the site stop
loading on Underdog. Fix:

    1. Download the current rankings CSV from Underdog (My Rankings -> Export).
    2. python scripts/build_underdog_ids.py "path/to/rankings-....csv"
    3. python scripts/bundle_lookups.py
    4. Bump the ?v= on the data/_bundle_lookups.js script tag in index.html.

Output: data/underdog_ids.js with two maps, both keyed by the SITE player
name (d.js `n` field, which is what the export button looks up):
    window.UNDERDOG_IDS  = { "Site Name": "underdog-uuid", ... }
    window.UNDERDOG_META = { "Site Name": {f, l, sal, tm}, ... }
UNDERDOG_META carries Underdog's own firstName/lastName spelling, salary and
team name so the exported CSV matches Underdog's current schema exactly.
"""
import csv
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D_JS = ROOT / "data" / "d.js"
OUT = ROOT / "data" / "underdog_ids.js"

# Site-name -> Underdog-name spelling differences (normalized form on both sides).
ALIASES = {
    "kenneth gainwell": "kenny gainwell",
    "marquise brown": "hollywood brown",
    "josh palmer": "joshua palmer",
    "cam ward": "cameron ward",
    "hollywood brown": "marquise brown",  # allow either direction
}

SUFFIXES = re.compile(r"\s+(jr|sr|ii|iii|iv|v)$")


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s or "").encode("ascii", "ignore").decode()
    s = s.lower().strip()
    s = re.sub(r"[.'\-]", "", s)
    s = SUFFIXES.sub("", s)
    s = re.sub(r"\s+", " ", s)
    return s


def load_d_players():
    raw = D_JS.read_text(encoding="utf-8")
    start = raw.index("[", raw.index("const D"))
    end = raw.rindex("}]") + 2
    players = json.loads(raw[start:end])
    return [(p["n"], p.get("s", ""), p.get("t", "")) for p in players]


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    ud_csv = Path(sys.argv[1])
    with open(ud_csv, newline="", encoding="utf-8-sig") as f:
        pool = list(csv.DictReader(f))

    by_name = {}
    by_last = {}
    for r in pool:
        full = norm(r["firstName"] + " " + r["lastName"])
        by_name.setdefault(full, []).append(r)
        by_last.setdefault(norm(r["lastName"]), []).append(r)

    d_players = load_d_players()
    ids, meta = {}, {}
    unmatched = []

    for name, pos, team in d_players:
        k = norm(name)
        cands = by_name.get(k) or by_name.get(ALIASES.get(k, "")) or []
        if not cands:
            # fallback: same last name + first initial + same team
            last = k.split(" ")[-1] if " " in k else k
            cands = [
                r for r in by_last.get(last, [])
                if norm(r["firstName"])[:1] == k[:1] and r["teamName"] == team
            ]
        if len(cands) > 1:
            same_team = [c for c in cands if c["teamName"] == team]
            pick_pool = same_team or cands
            same_pos = [c for c in pick_pool if c["slotName"] == pos]
            cands = same_pos or pick_pool
        if not cands:
            unmatched.append(f"{name} ({pos} {team})")
            continue
        r = cands[0]
        ids[name] = r["id"]
        meta[name] = {
            "f": r["firstName"],
            "l": r["lastName"],
            "sal": r.get("salary", ""),
            "tm": r["teamName"],
            "pid": r.get("playerId", ""),
        }

    header = (
        "/* Underdog player ID map — generated by scripts/build_underdog_ids.py\n"
        "   from Underdog's rankings CSV export. Keys are site (d.js) player names.\n"
        "   Re-run that script with a fresh Underdog export whenever Underdog\n"
        "   rotates player IDs (rankings uploads start failing). */\n"
    )
    body = (
        "window.UNDERDOG_IDS=" + json.dumps(ids, ensure_ascii=False, separators=(",", ":")) + ";\n"
        "window.UNDERDOG_META=" + json.dumps(meta, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    OUT.write_text(header + body, encoding="utf-8")

    print(f"d.js players: {len(d_players)}  Underdog pool: {len(pool)}")
    print(f"matched: {len(ids)}  unmatched: {len(unmatched)}")
    if unmatched:
        print("\nUnmatched (skipped in export — not in Underdog's current pool):")
        for u in unmatched:
            print("  " + u)
    print(f"\nWrote {OUT}")
    print("Next: python scripts/bundle_lookups.py  +  bump ?v= on _bundle_lookups.js in index.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
