"""Build data/contracts_history.js from the nflverse/OverTheCap contracts dataset.

Source: https://github.com/nflverse/nflverse-data/releases/download/contracts/historical_contracts.parquet
(the .csv.gz asset in the same release has been frozen since 2022-05 - do not use it; the
parquet is refreshed by nflverse daily and carries money in MILLIONS, converted to dollars here).
Filter: QB/RB/WR/TE/FB/K. Names canonicalized to ALL_PLAYERS_DB where possible.

Output (window.CONTRACTS_DB):
  { "Player Name": [ {t:"KC", y:2020, n:10, v:450000000, a:45000000, g:141482905, p:0.227}, ... ] }
  t=team, y=year signed, n=contract years, v=total value, a=APY, g=guaranteed, p=APY % of cap
Sorted newest-first per player.

Usage: python scripts/build_contracts.py   (weekly via scripts/route_pct_daily.ps1 step 7)
"""
import io, json, math, os, re, sys
import requests
import pyarrow.parquet as pq

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = "https://github.com/nflverse/nflverse-data/releases/download/contracts/historical_contracts.parquet"
COLS = ["player", "position", "team", "year_signed", "years", "value", "apy", "guaranteed", "apy_cap_pct"]
POS = {"QB", "RB", "WR", "TE", "FB", "K"}
TEAM = {
    "Cardinals": "ARI", "Falcons": "ATL", "Ravens": "BAL", "Bills": "BUF",
    "Panthers": "CAR", "Bears": "CHI", "Bengals": "CIN", "Browns": "CLE",
    "Cowboys": "DAL", "Broncos": "DEN", "Lions": "DET", "Packers": "GB",
    "Texans": "HOU", "Colts": "IND", "Jaguars": "JAX", "Chiefs": "KC",
    "Raiders": "LV", "Chargers": "LAC", "Rams": "LAR", "Dolphins": "MIA",
    "Vikings": "MIN", "Patriots": "NE", "Saints": "NO", "Giants": "NYG",
    "Jets": "NYJ", "Eagles": "PHI", "Steelers": "PIT", "49ers": "SF",
    "Seahawks": "SEA", "Buccaneers": "TB", "Titans": "TEN",
    "Commanders": "WAS", "Redskins": "WAS", "Football Team": "WAS", "Washington": "WAS",
}


def norm(n):
    n = re.sub(r"\b(jr|sr|ii|iii|iv|v)\.?$", "", n.lower().strip())
    return re.sub(r"[^a-z]", "", n)


def load_js_obj(path):
    txt = open(path, encoding="utf-8").read()
    txt = txt[txt.index("=") + 1:].strip().rstrip(";")
    return json.loads(txt)


def num(s, cast=int, mult=1):
    try:
        v = float(s) * mult
        if math.isnan(v) or math.isinf(v):
            return None
        return cast(round(v)) if cast is int else cast(v)
    except (TypeError, ValueError):
        return None


def main():
    allp = load_js_obj(os.path.join(ROOT, "data", "all_players.js"))
    canon = {}
    for p in allp:
        canon.setdefault(norm(p["name"]), p["name"])

    raw = requests.get(URL, timeout=120)
    raw.raise_for_status()
    rows = pq.read_table(io.BytesIO(raw.content), columns=COLS).to_pylist()
    out = {}
    kept = 0
    for row in rows:
        if row["position"] not in POS or not row["player"]:
            continue
        y = num(row["year_signed"])
        if not y:
            continue
        row["team"] = row["team"] or ""
        name = canon.get(norm(row["player"]), row["player"])
        c = {"t": TEAM.get(row["team"], row["team"]), "y": y}
        n = num(row["years"])
        if n:
            c["n"] = n
        for src, key in (("value", "v"), ("apy", "a"), ("guaranteed", "g")):
            v = num(row[src], mult=1e6)
            if v is not None:
                c[key] = v
        p = num(row["apy_cap_pct"], float)
        if p is not None:
            c["p"] = round(p, 3)
        out.setdefault(name, []).append(c)
        kept += 1
    for name in out:
        out[name].sort(key=lambda c: -c["y"])

    body = json.dumps(out, separators=(",", ":"), ensure_ascii=False)
    js = ("// Generated by scripts/build_contracts.py — OverTheCap contract history via nflverse\n"
          "// t=team y=signed n=years v=value a=APY g=guaranteed p=APY % of cap at signing\n"
          "window.CONTRACTS_DB=" + body + ";\n")
    dest = os.path.join(ROOT, "data", "contracts_history.js")
    # Unattended weekly runs: never publish a truncated upstream file over a good one.
    if os.path.exists(dest):
        old = open(dest, encoding="utf-8").read()
        mark = "window.CONTRACTS_DB="
        if mark in old:
            prev = len(json.loads(old[old.index(mark) + len(mark):].strip().rstrip(";")))
            if len(out) < prev * 0.9:
                print(f"ABORT: {len(out)} players vs {prev} on disk - upstream file looks truncated, nothing written")
                sys.exit(3)
    open(dest, "w", encoding="utf-8", newline="\n").write(js)
    print(f"Wrote {dest}: {len(out)} players, {kept} contracts, {len(js)//1024} KB")


if __name__ == "__main__":
    main()
