"""Last season's points allowed by position - the PRIOR for the site's opponent grade.

Writes data/fpa_prior_<season>.js: for every team, the schedule-adjusted,
touchdown-neutral fantasy points it allowed per game to QB / RB / WR / TE, and
(DST) the points opposing D/STs scored against its offense with defensive and
return touchdowns removed. app.js (_mtObservedFpa) blends this with the same
number from the current season, weight games / (games + k) on the current one.

Why this shape: scripts/research_opp_grade_schemes.py (2016-25) - touchdown-
neutral points with last season as the prior beat every other version tested,
including dropping the past entirely after week 4.

Touchdown-neutral = actual TDs out, the league TD rate on the yards allowed in
(TDN_* below, 2014-25 pooled). pull_postgame_stats.py uses the same constants
for the in-season side - keep the two in sync.

Run once a year after the regular season:  python scripts/build_fpa_prior.py --season 2025
(scripts/january_outcomes_refresh.ps1 does it on the second Tuesday of January.) app.js picks
window.FPA_PRIOR_<season of the points-allowed file - 1>, so the season rollover only has to
point the <script> tag in index.html at the new file.
Source: nflverse player-week + team-week stats. Final regular-season week dropped.
"""
import argparse
import json
import os
import sys
import time

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from research_dst_opponent_vs_quality import build as build_dst, fetch as fetch_dst  # noqa: E402
from research_opp_grade_schemes import player_games  # noqa: E402
from research_preseason_fade import sched_adjust  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TDN_PASS, TDN_RUSH, TDN_REC = 0.00626, 0.00759, 0.00623   # league TDs per yard, 2014-25
ABBR_FIX = {'LA': 'LAR', 'WSH': 'WAS', 'JAC': 'JAX', 'OAK': 'LV', 'SD': 'LAC'}
POS = ('QB', 'RB', 'WR', 'TE')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--season', type=int, required=True)
    args = ap.parse_args()
    y = args.season

    g = player_games(y)
    g['v'] = (g['v'] - 4 * g['ptd'] - 6 * (g['rtd'] + g['rectd'])
              + 4 * TDN_PASS * g['pyd'] + 6 * (TDN_RUSH * g['ryd'] + TDN_REC * g['recyd']))
    g = g[['week', 'd', 'o', 'pos', 'v']]
    stats, scored = fetch_dst([y])
    dst = build_dst(stats, scored).dropna(subset=['dst_fpts'])
    dst['v'] = dst['dst_fpts'] - 6.0 * (dst['def_tds'] + dst['special_teams_tds'])
    dst = dst.rename(columns={'opponent_team': 'd', 'team': 'o'})[['week', 'd', 'o', 'v']]
    dst['pos'] = 'DST'
    g = pd.concat([g, dst], ignore_index=True)
    g = g[g['week'] < g['week'].max()]

    out = {}
    for pos in POS + ('DST',):
        f = g[g['pos'] == pos]
        fit = sched_adjust(list(zip(f['d'], f['o'], f['v'])))
        out[pos] = {ABBR_FIX.get(t, t): round(v, 2) for t, v in sorted(fit.items())}
        if len(out[pos]) != 32:
            print('WARNING: %s has %d teams' % (pos, len(out[pos])), file=sys.stderr)
    obj = {'season': y, 'basis': 'half_ppr, touchdown-neutral, schedule-adjusted per game, final week dropped',
           'built': time.strftime('%Y-%m-%d'), 'pos': out}
    path = os.path.join(ROOT, 'data', 'fpa_prior_%d.js' % y)
    txt = ('// AUTO-GENERATED by scripts/build_fpa_prior.py - do not hand-edit.\n'
           '// %d points ALLOWED per game by position, schedule-adjusted and touchdown-neutral (actual TDs swapped for the\n'
           '// league TD rate on the yards allowed). DST = points opposing D/STs scored against this OFFENSE, defensive and\n'
           '// return TDs removed. The prior for the opponent grade (app.js _mtObservedFpa); the in-season side comes from\n'
           '// fpa_%d.js (<POS>_tdn keys).\n'
           'window.FPA_PRIOR_%d = %s;\n' % (y, y + 1, y, json.dumps(obj, separators=(',', ':'))))
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(txt)
    print('wrote %s' % path)
    for pos in out:
        r = sorted(out[pos].items(), key=lambda kv: -kv[1])
        print('  %-3s most: %s   fewest: %s' % (pos, ', '.join('%s %.1f' % kv for kv in r[:3]), ', '.join('%s %.1f' % kv for kv in r[-3:])))


if __name__ == '__main__':
    main()
