#!/usr/bin/env python3
"""Concatenate the small stable lookup-table data scripts into a single bundle.

Output: data/_bundle_lookups.js — replaces 42 individual script tags in index.html.

Re-run this script whenever one of the BUNDLED_FILES is edited by hand. The
pipeline-regenerated files (d.js, all_players.js, weekly_stats_active.js, etc.)
are NOT in this list — they keep loading as separate script tags so the pipeline
doesn't need to know about bundling.

Usage:
    python scripts/bundle_lookups.py
"""
from pathlib import Path
import sys

# Order matches the order these scripts currently load in index.html (lines 3351-3392).
# If you reorder, edit both this list AND the script tag in index.html in lockstep.
BUNDLED_FILES = [
    "ktc_rankings.js",
    "underdog_ids.js",
    "legend_birth_years.js",
    "pff_qb_risk.js",
    "college_logo_ids.js",
    "fallback_espn_ids.js",
    "legend_bio.js",
    "qb_big_time.js",
    "qb_turnover_rate.js",
    "retired_espn_ids.js",
    "school_conferences.js",
    "school_keywords.js",
    "school_norm.js",
    "team_divisions.js",
    "team_keywords.js",
    "nfl_logo_map.js",
    "all_nfl_teams.js",
    "badges.js",
    "bbm_first_pos_by_round.js",
    "bbm_pick_by_rank_round.js",
    "bbm_path_optimal.js",
    "bbm_optimizer_data.js",
    "bbm_stack_comp_multistage.js",
    "bbm_structural_multistage.js",
    "college_pos_override.js",
    "colorways.js",
    "conf_keywords.js",
    "cs_aliases.js",
    "full_to_code.js",
    "ht_ranges.js",
    "ih_type_mults.js",
    "inj_type_multipliers.js",
    "jm_ceiling_weights.js",
    "jm_devy_ceiling.js",
    "jm_devy_floor.js",
    "jm_weights.js",
    "pick_defs.js",
    "prod_ranges.js",
    "prospect_aliases.js",
    "team_2025_fix.js",
    "team_abbr_map.js",
    "team_logo_ids.js",
]

OUT = "_bundle_lookups.js"


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    data_dir = root / "data"
    missing = [f for f in BUNDLED_FILES if not (data_dir / f).exists()]
    if missing:
        print(f"ERROR: missing files: {missing}", file=sys.stderr)
        return 1

    parts: list[str] = [
        "/* AUTO-GENERATED by scripts/bundle_lookups.py — do not edit by hand.",
        f"   Concatenation of {len(BUNDLED_FILES)} stable lookup tables, in load order.",
        "   Edit a source file then re-run the script to refresh this bundle. */",
        "",
    ]
    total_bytes = 0
    for name in BUNDLED_FILES:
        path = data_dir / name
        content = path.read_text(encoding="utf-8")
        total_bytes += len(content.encode("utf-8"))
        parts.append(f"// ===== {name} =====")
        # Ensure each file ends with a newline + statement terminator so the
        # next file's top-level statement can't accidentally chain onto the
        # previous file's last expression.
        if not content.endswith("\n"):
            content += "\n"
        parts.append(content)
        parts.append(";")  # belt-and-suspenders statement separator
        parts.append("")

    out_path = data_dir / OUT
    out_path.write_text("\n".join(parts), encoding="utf-8")
    out_bytes = out_path.stat().st_size
    print(f"Wrote {out_path} ({out_bytes:,} bytes, sum of inputs: {total_bytes:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
