"""ESPN depth charts (offense: QB / RB / WR / TE by rank) -> data/depth_charts_2026.js / .json.

Source: site.api.espn.com/apis/site/v2/sports/football/nfl/teams/<id>/depthcharts
(one call per team, athlete display names inline; the offensive formation
item — "3WR 1TE" etc. — carries qb/rb/wr/te with rank-ordered athletes).
ESPN depth charts are the site's starter authority elsewhere
(feedback_starters_espn_depth_charts), so they are the natural weight for
WHO absorbs a ruled-out teammate's touches in the sims.

  python scripts/pull_depth_charts.py        # write data/depth_charts_2026.js(.json)
  python scripts/pull_depth_charts.py --dry  # print summary, write nothing

Consumers: sim_lab/refresh_data.py copies the JSON into sim_lab/data/
sim_depth.js (window.SIM_DEPTH_2026) for the engine's vacated-opportunity
redistribution (depth rank weights the healthy group's share).

Output: window.DEPTH_2026 = {updated, src, teams: {ABBR: {QB: [names by rank],
RB: [...], WR: [...], TE: [...]}}}
"""
import json
import os
import sys
import time
from datetime import datetime, timezone

import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data', 'depth_charts_2026.js')
OUT_JSON = os.path.join(ROOT, 'data', 'depth_charts_2026.json')
TEAMS_URL = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams?limit=40'
DEPTH_URL = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/{id}/depthcharts'
# site.api.espn.com 403s browser-style UAs from scripts but serves curl's
# (same gotcha as pull_weather.py's scoreboard call) — keep it curl-like.
UA = {'User-Agent': 'curl/8.4.0'}
ABBR_FIX = {'WSH': 'WAS', 'JAC': 'JAX', 'LA': 'LAR', 'OAK': 'LV', 'SD': 'LAC'}
POS_KEYS = {'qb': 'QB', 'rb': 'RB', 'wr': 'WR', 'te': 'TE'}


def pull_team(tid):
    r = requests.get(DEPTH_URL.format(id=tid), headers=UA, timeout=30)
    r.raise_for_status()
    j = r.json()
    items = j.get('depthchart') or []
    # offensive formation = the item whose positions include a qb slot
    off = None
    for it in items:
        pos = it.get('positions') or {}
        if 'qb' in pos:
            off = it
            break
    if not off:
        return None
    out = {}
    positions = off.get('positions') or {}
    for key, label in POS_KEYS.items():
        # ESPN keys receivers by SLOT (wr1 / wr2 / wr3 in a 3WR set, wr1 / wr2
        # in 2WR sets), never a bare 'wr' (2026-09-11 fix: every team lacked a
        # WR list). Interleave the slots by depth: all slot starters first,
        # then every slot's second man, and so on.
        slots = [positions[key]] if positions.get(key) else                 [positions[k] for k in sorted(positions) if k.startswith(key) and k[len(key):].isdigit()]
        if not slots:
            continue
        ranked = []
        for sl in slots:
            ath = sorted(sl.get('athletes') or [], key=lambda a: a.get('rank') or 99)
            ranked.append([(a.get('displayName') or '').strip() for a in ath])
        names = []
        for depth in range(max(len(r) for r in ranked)):
            for r in ranked:
                if depth < len(r) and r[depth] and r[depth] not in names:
                    names.append(r[depth])
        if names:
            out[label] = names
    return out


def main():
    dry = '--dry' in sys.argv
    r = requests.get(TEAMS_URL, headers=UA, timeout=30)
    r.raise_for_status()
    teams = [(t['team']['id'], ABBR_FIX.get(t['team']['abbreviation'], t['team']['abbreviation']))
             for t in r.json()['sports'][0]['leagues'][0]['teams']]
    charts = {}
    misses = []
    for tid, abbr in teams:
        try:
            dc = pull_team(tid)
            if dc:
                charts[abbr] = dc
            else:
                misses.append(abbr)
        except Exception as e:
            misses.append(f'{abbr}({e})')
        time.sleep(0.25)
    if len(charts) < 24:
        sys.exit(f'!! only {len(charts)} teams resolved ({", ".join(misses)}) — nothing written')
    print(f'{len(charts)} teams; misses: {", ".join(misses) or "none"}')
    for abbr in ('NE', 'SEA'):
        if abbr in charts:
            print(f'  {abbr} RB: {charts[abbr].get("RB", [])[:4]}  QB: {charts[abbr].get("QB", [])[:2]}')
    if dry:
        return
    payload = {'updated': datetime.now(timezone.utc).isoformat(), 'src': 'espn depthcharts', 'teams': charts}
    body = ('// Auto-generated by scripts/pull_depth_charts.py — do not hand-edit.\n'
            '// ESPN offensive depth charts: QB/RB/WR/TE names by rank per team.\n'
            'window.DEPTH_2026 = ' + json.dumps(payload, separators=(',', ':'), ensure_ascii=False) + ';\n')
    old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    open(OUT_JSON, 'w', encoding='utf-8', newline='\n').write(
        json.dumps(payload, separators=(',', ':'), ensure_ascii=False))
    print(f'data/depth_charts_2026.js written ({len(body):,} bytes, {"changed" if body != old else "no change"})')


if __name__ == '__main__':
    main()
