"""Weekly consensus projections: Sleeper -> data/weekly_projections.js.

The weekly PROJ PPG chain (app.js _weeklyAdjustPpg) scores posted prop lines
first (books are primary, Jack's rule); players WITHOUT a prop board fell to
the position-blind heuristic (season PPG x team-total x opp-defense). This
feed gives those players a real per-week number instead.

Week selection: Sleeper /v1/state/nfl. During the regular season, the live
week; preseason/offseason, regular-season week 1 (Sleeper publishes W1
projections in August). Values are Sleeper's pts_half_ppr / pts_ppr /
pts_std per player, top 600 by half-PPR. DEF is skipped - the DST branch in
_weeklyAdjustPpg returns before the consensus slot.

Usage: python scripts/pull_weekly_projections.py [--dry]
Runs as Phase J of the 9am daily job.
"""
import json
import os
import sys
from datetime import datetime, timezone

import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data', 'weekly_projections.js')
STATE_URL = 'https://api.sleeper.app/v1/state/nfl'
PROJ_URL = ('https://api.sleeper.com/projections/nfl/{season}/{week}'
            '?season_type=regular'
            '&position[]=QB&position[]=RB&position[]=WR&position[]=TE&position[]=K'
            '&order_by=pts_half_ppr')
CAP = 600


def main():
    dry = '--dry' in sys.argv
    state = requests.get(STATE_URL, timeout=30).json()
    season = state.get('season')
    week = state.get('week') if state.get('season_type') == 'regular' else 1
    if not season or not week:
        sys.exit(f'!! bad state response: {state}')
    r = requests.get(PROJ_URL.format(season=season, week=week), timeout=60)
    r.raise_for_status()
    rows = r.json()
    players = {}
    for row in rows:
        st = row.get('stats') or {}
        pl = row.get('player') or {}
        h = st.get('pts_half_ppr')
        if h is None:
            continue
        name = (pl.get('first_name', '') + ' ' + pl.get('last_name', '')).strip()
        if not name or name in players:
            continue
        players[name] = {
            'h': round(h, 1),
            'p': round(st.get('pts_ppr', h), 1),
            's': round(st.get('pts_std', h), 1),
        }
        if len(players) >= CAP:
            break
    if len(players) < 100:
        sys.exit(f'!! only {len(players)} projections parsed — refusing to write')
    print(f'{len(players)} weekly projections (season {season} week {week})')
    if dry:
        for n, v in list(players.items())[:8]:
            print(f'  {n}: half {v["h"]}')
        return
    payload = {
        'updated': datetime.now(timezone.utc).isoformat(),
        'src': 'sleeper',
        'season': int(season),
        'week': int(week),
        'players': players,
    }
    body = ('// Auto-generated by scripts/pull_weekly_projections.py — do not hand-edit.\n'
            '// Consensus weekly projections consumed by _weeklyAdjustPpg in app.js.\n'
            'window.WEEKLY_PROJ = '
            + json.dumps(payload, separators=(',', ':'), ensure_ascii=False) + ';\n')
    old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    print(f'data/weekly_projections.js written ({len(body):,} bytes, '
          f'{"changed" if body != old else "no change"})')


if __name__ == '__main__':
    main()
