"""Daily injury pull: Sleeper API -> data/injury_updates.js.

Replaces the never-automated Firestore site_data/injury_updates feed (the old
injury_scanner.py --firestore flow printed console-paste code that was never
run). This writes a static data file that rides the same commit+push pipeline
as every other data file, so freshness = the daily 9am job + any manual run.

  python scripts/pull_injuries.py        # write data/injury_updates.js
  python scripts/pull_injuries.py --dry  # print summary, write nothing

Consumed by the [InjuryUpdates] merge block in app.js: exact-name match into
D[].inj (never overwrites a hand-set tag), `cleared` un-sets feed-applied tags
for players Sleeper now shows healthy, and an 8-day staleness guard on
`updated` means a dead job fails safe (stale tags stop applying rather than
lingering).
"""
import json
import sys
import os
from datetime import datetime, timezone

import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data', 'injury_updates.js')
SLEEPER_PLAYERS_URL = 'https://api.sleeper.app/v1/players/nfl'
POSITIONS = ('QB', 'RB', 'WR', 'TE', 'K')

STATUS_MAP = {
    'IR': 'IR',
    'Out': 'Out',
    'Doubtful': 'Doubtful',
    'Questionable': 'Questionable',
    'PUP': 'PUP',
    'Sus': 'Suspended',
    'Suspension': 'Suspended',
    'DNR': 'DNR',
    'NA': None,
}


def build(players):
    injured = {}
    cleared = []
    for p in players.values():
        pos = p.get('position')
        if pos not in POSITIONS:
            continue
        name = p.get('full_name') or (
            (p.get('first_name', '') + ' ' + p.get('last_name', '')).strip())
        if not name:
            continue
        team = p.get('team')
        status = p.get('injury_status')
        if not status or status == 'Active':
            # Healthy: only relevant for clearing if they're on a roster.
            if team:
                cleared.append(name)
            continue
        mapped = STATUS_MAP.get(status, status)
        if not mapped:
            continue
        body = p.get('injury_body_part') or ''
        parts = [body, mapped] if body else [mapped]
        notes = p.get('injury_notes') or ''
        if notes and len(notes) <= 90:
            low = notes.lower()
            if any(k in low for k in ('week', 'month', 'season', 'acl',
                                      'achilles', 'surgery', '2026', '2027')):
                parts.append(notes)
        injured[name] = ', '.join(parts)
    return injured, sorted(cleared)


def main():
    dry = '--dry' in sys.argv
    r = requests.get(SLEEPER_PLAYERS_URL, timeout=60)
    r.raise_for_status()
    players = r.json()
    injured, cleared = build(players)
    if len(injured) < 20:
        # A near-empty in-season injury list means the pull is broken, not
        # that the NFL got healthy. Keep the previous file.
        print(f'!! only {len(injured)} injuries parsed — refusing to write')
        sys.exit(1)
    print(f'{len(injured)} injured, {len(cleared)} healthy-cleared '
          f'across {"/".join(POSITIONS)}')
    if dry:
        for n, t in sorted(injured.items())[:15]:
            print(f'  {n}: {t}')
        return
    payload = {
        'updated': datetime.now(timezone.utc).isoformat(),
        'source': 'sleeper',
        'players': injured,
        'cleared': cleared,
    }
    body = ('// Auto-generated by scripts/pull_injuries.py — do not hand-edit.\n'
            '// Sleeper injury feed: applied by the [InjuryUpdates] block in app.js.\n'
            'window.INJURY_UPDATES = '
            + json.dumps(payload, indent=1, ensure_ascii=False) + ';\n')
    old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    print(f'data/injury_updates.js written ({len(body):,} bytes, '
          f'{"changed" if body != old else "no change"})')


if __name__ == '__main__':
    main()
